commit progress organisation metrics #3146
AtlasOfLivingAustralia/ecodata pull request #982
Opened 2024-06-25 00:15 UTC by salomon-j

2024-06-25 03:21 UTC, chrisala requested changes

2024-06-25 03:21 UTC, chrisala commented on grails-app/controllers/au/org/ala/ecodata/OrganisationController.groovy
> +        boolean targetsOnly = false
Organisations don't have a concept of targets so we should delete targetsOnly and includeTargets

2024-06-25 03:21 UTC, chrisala commented on grails-app/services/au/org/ala/ecodata/OrganisationService.groovy
> +        def org = Organisation.findByOrganisationId(id)
Organisations don't have a concept of targets so we should delete targetsOnly and includeTargets

2024-06-25 03:21 UTC, chrisala commented on grails-app/services/au/org/ala/ecodata/OrganisationService.groovy
> +            if (includeTargets) {
Delete this section as organisations cannot have targets

2024-07-08 00:18 UTC, chrisala commented
@salomon-j this got moved to a different branch didn't it?  It is safe to close this?

2024-07-08 05:21 UTC, salomon-j commented
> @salomon-j this got moved to a different branch didn't it? It is safe to close this?

yes it is safe to close it, I've created a new branch that was merged into master.

2024-07-08 05:21 UTC, closed without merging